services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Markocupic\ContaoArticleClassSelectBundle\:
        resource: ../src/
        exclude: ../src/{ContaoManager,DependencyInjection}
